site_name: Learning ROS with FRC
theme: 
  name: material
  palette:
    scheme: slate
    primary: green
    accent: yellow
  highlightjs: true
  hljs_languages:
    - bash

nav:
  - Getting Started: index.md
  - ROS Installation & Setup: rossetup.md
  - SSH GUI Forwarding: guiforwarding.md
  - RPi on RoboRIO network: frcpi.md
  - Useful Commands: linuxcmds.md
  - Further Reading: links.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - admonition
  - toc